### ISSUE TITLE
Multiple Ciphertexts Handling 

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#1]
[Discussed issue in Pyfhel repository](https://github.com/ibarrond/Pyfhel/issues/163)

**Comment by ShokofehVS** [comment]
**Description**

While trying to execute the `calculate_msr` with `no_ciphertexts = 1` 
failed with ERROR

**Full logs**
```
Traceback (most recent call last):
  File "/home/user/Documents/github/SecBic-CCA/SecBiclib/algorithms/cipher_operations.py", line 286, in <module>
    sup_plain_list, data_sizes = zip(*[enlarge(plain_sub) for plain_sub in plain_list])
  File "/home/user/Documents/github/SecBic-CCA/SecBiclib/algorithms/cipher_operations.py", line 286, in <listcomp>
    sup_plain_list, data_sizes = zip(*[enlarge(plain_sub) for plain_sub in plain_list])
  File "/home/user/Documents/github/SecBic-CCA/SecBiclib/algorithms/cipher_operations.py", line 14, in enlarge
    N_rows,N_cols=np.shape(array)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ibarrond** [comment]
That just means that `array` is of dimension 1, thus it returns a single value (the number of elements). Your code is expecting two numbers (N_rows and N_cols), but got only one, hence the error.

**Comment by ShokofehVS** [comment]
Yes, that's true. I need to look into the code and make some changes as of now it won't accept single ciphertext.

**Comment by ShokofehVS** [comment]
Current problem: 
with considering ciphertexts in list -> **scale out of bounds**: 

1. Checking all multiplications, and shifts to have been implemented with Rescaling  (Almost done)
2. Inefficient implemented logic of handling lists of ciphertexts (more probable- current approach) 

Without considering list of ciphertexts -> ckks nSlots but no scale out of bounds problems

**Comment by ShokofehVS** [comment]
Shifting ciphertexts in list for computing sums of each axes influence the source ciphertexts then make the rest of computation incorrect => check the function inside the `_list_shift`
