### ISSUE TITLE
Benchmarking Single Ciphertexts - Node Deletion Steps

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#11]
1. Comparison of `encryptedmsr` with its original counterpart for single ciphertexts:

1.1.  incorrect results after applying subtraction and addition over `ciphertext , cipher_row_mean , cipher_col_mean , cipher_data_mean`:
Hypothesis:
* different scale of each encrypted values -> refilling ciphertexts with proper values to the number of elements  
* incorrect computation of mean for whole matrix/sub_matrix

**Comment by ibarrond** [comment]
Can you share/point to the code generating this error?

**Comment by ShokofehVS** [comment]
For clarifying the problem, I bring an example: 
	         			
plaintext: [[6 3 2]
	     [1 4 5]
	     [2 8 4]
	     [3 1 6]] (4, 3) => [6 3 2 1 4 5 2 8 4 3 1 6] (flatted for encryption - ciphertext)

row_mean: [3.6
	           3.3
	           4.6
	            3.3] (4,1)  => [3.6 3.3 4.5 3.3] (flatted during computation  - cipher_row_mean)

col_mean: [3 4 4.25] (3,) => [3 4 4.25] (flatted during computation  - cipher_col_mean)

data_mean: 3.7 => [3.7] (flatted during computation  - cipher_data_mean)

residues = [`residues = ciphertext - cipher_row_mean - cipher_col_mean + cipher_data_mean`](https://github.com/ShokofehVS/SecBic-CCA/blob/2f4359aa13886ff7d3b5943b22e7ed7ed7bb38cc/SecBiclib/algorithms/encryptedmsr.py#L240) 
=[6 3 2 1 4 5 2 8 4 3 1 6] - [3.6 3.3 4.5 3.3] - [3 4 4.25]  + [3.7] 

One approach came to my mind was getting help from rotation in Pyfhel. I get several test for [computing col_mean](https://github.com/ShokofehVS/SecBic-CCA/blob/2f4359aa13886ff7d3b5943b22e7ed7ed7bb38cc/SecBiclib/algorithms/encryptedmsr.py#L154) which works fine but I have still problem in [row_mean](https://github.com/ShokofehVS/SecBic-CCA/blob/2f4359aa13886ff7d3b5943b22e7ed7ed7bb38cc/SecBiclib/algorithms/encryptedmsr.py#L139)  which seems it's not that much easy to use rotation. For cipher_data_mean, I'm still unsure of [computing mean](https://github.com/ShokofehVS/SecBic-CCA/blob/2f4359aa13886ff7d3b5943b22e7ed7ed7bb38cc/SecBiclib/algorithms/encryptedmsr.py#L170) in this way we are doing so.

**Comment by ibarrond** [comment]
I still don't see what the problem is. Can you share a piece of code that I can execute (with the minimal size possible, to make it easier), the result you need and the result that you are getting?

**Comment by ShokofehVS** [comment]
Alberto, I tried to simplified the code into an executable script with sample data and desired output but not sure that it's understandable now or not. Let me know if you have any issue.

**Comment by ShokofehVS** [comment]
Benchmarking No. 1: finished and the first two problems are now fixed.
