### ISSUE TITLE
Dependency Issues -- ModuleNotFoundError: No module named 'SecBiclib'

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#2]
**Description**

While trying to execute the scripts by terminal; they fail with: "ModuleNotFoundError: No module named ... (for example SecBiclib) -- _Dependencies issues_

**Command To Reproduce Error**

`python3 SecBiclib/scripts/secured_cheng_church_yeast.py`

**Full logs:**
```
Traceback (most recent call last):
  File "scripts/secured_cheng_church_yeast.py", line 2, in <module>
    from SecBiclib.algorithms import SecuredChengChurchAlgorithm
ModuleNotFoundError: No module named 'SecBiclib'

```

**Comment by julrau92** [comment]
### Installation with pip:
**Cause:** 
The sub-packages were not included in the setup.py file and therefore not installed.

**Solution:**
I Modified the setup.py file in _dev_debug_ to include sub-packages with find_packages() method.
(working for me, installed with pip)

### Use without install:
**Cause:** 
Trying to import SecBiclib from a script inside SecBiclib/scripts/ will run it from this path and therefore won't find SecBiclib/ there for imports.

**Solution:**
Copy any script to be used and place it outside of SecBiclib directory. Run it from there, then it will find SecBiclib and do the 
imports without errors

_Alternatively one could also add the location of SecBiclib to the PYTHONPATH variable manually._

**Comment by ShokofehVS** [comment]
@julrau92: could you please write down the steps you solve this problem, thereafter I can update the README file? 

**Installation with pip**
Still I have problem in finding packages, here are the steps I followed to test the modified setup file:

1.   git clone https://github.com/ShokofehVS/SecBic-CCA.git
2.   cd SecBic-CCA
3.   pip install -r requirements.txt (we have follow up issue here)
4.   sudo python3 setup.py install (Finished processing dependencies for SecBiclib==0.1)
5.   python3 SecBiclib/scripts/secured_cheng_church_yeast.py 
```
Traceback (most recent call last):
  File "SecBiclib/scripts/secured_cheng_church_yeast.py", line 2, in <module>
    from SecBiclib.algorithms import SecuredChengChurchAlgorithm
ModuleNotFoundError: No module named 'SecBiclib.algorithms
```
**Use without Install**
Well, this approach I followed in the previous project, but it's better to make everything in its directory. 

Thank you!

**Comment by julrau92** [comment]
**Installation with pip**

Try using: "pip3 install ." (instead of the manual python3 setup.py install) 
from the main directory which contains the setup.py file. That's how it worked for me.

**Modifications**

I just modified the  the **setup. py** file like this:

```python

from setuptools import setup, find_packages
... 
packages=find_packages(), # not: packages=['SecBiclib'],
include_package_data=True,
... 

```

**Comment by ShokofehVS** [comment]
Confirm the problem has been solved. 
Then @julrau92 should the README file be like below?

1. git clone https://github.com/ShokofehVS/SecBic-CCA.git
2. cd SecBic-CCA
3. pip install -r requirements.txt (we have follow up issue here)
4. sudo pip3 install .
5. python3 SecBiclib/scripts/secured_cheng_church_yeast.py (as well for other python scripts)

**Comment by julrau92** [comment]
Yes, that's good :)
