### ISSUE TITLE
Evaluation of Ignoring Single Node Phase with FHE

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#9]
As of now the multiple node deletion phase is being computed with FHE (or later MPC) due to computational burden imposed by FHE. 

**This needs further to be evaluated in terms of overall privacy, and performance.

**Comment by ibarrond** [comment]
What mathematical functions are involved in this?

**Comment by ShokofehVS** [comment]
I just checked the implementation and made some mistakes as we're already computing the score for single removal of nodes (rows or cols) by FHE but it requires operations like the following which make me in doubt whether focusing on multiple node deletion is enough for whole node removal (which requires me to compare the time performance of these two approaches): 

1. Comparison of the score with the threshold
2. Since then find the largest calculated msr of the rows and that of columns (so called "d" value)
3. Afterwards, second comparison for removing the row or column whichever with the larger "d"

Despite multiple non-linear and linear functions, in the original experiment for some cases, it is advisable to use the Multiple Node Deletion before the matrix is reduced to a manageable size because of expensive updates.
